name: Fuzz

on:
  workflow_dispatch:

jobs:
  fuzz-all:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        func:
          - FuzzRemoveDuplicates
          - FuzzTrimEach
          - FuzzMap
          - FuzzFilter
          - FuzzFilterEmpty
          - FuzzJoin
          - FuzzReverse

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Run fuzz on ${{ matrix.func }}
        run: go test -fuzz=^${{ matrix.func }}$ -fuzztime 10s
